name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: pnpm

      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: DB 起動
        run: supabase start --exclude realtime,storage-api,imgproxy,inbucket,studio,edge-runtime

      - name: パッケージインストール
        run: pnpm install
      - name: アプリビルド
        run: pnpm build

      - name: Playwright ブラウザインストール
        run: pnpm exec playwright install --with-deps
      - name: テスト実行
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
